"""Needle-based skill and tool router for LocalCoder.

This module implements the Needle routing engine that:
1. Analyzes user intent
2. Selects appropriate skills
3. Routes to appropriate tools
4. Generates structured tool execution plans
"""

import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

from localcoder.config.settings import Settings
from localcoder.providers.ollama import OllamaMessage, OllamaProvider


@dataclass
class ToolCall:
    """A single tool call with arguments."""

    name: str
    arguments: dict[str, Any]
    description: str = ""


@dataclass
class SkillSelection:
    """Selected skill for a task."""

    name: str
    confidence: float
    reason: str


@dataclass
class ExecutionPlan:
    """Complete execution plan generated by Needle."""

    intent: str
    skills: list[SkillSelection] = field(default_factory=list)
    tools: list[ToolCall] = field(default_factory=list)
    requires_confirmation: bool = False
    summary: str = ""


class NeedleRouter:
    """
    Needle-based routing engine for skill and tool selection.

    Uses a local model to analyze intent and select appropriate
    skills and tools for autonomous execution.
    """

    def __init__(
        self,
        settings: Settings,
        available_tools: list[dict],
        available_skills: list[dict],
    ):
        self.settings = settings
        self.available_tools = available_tools
        self.available_skills = available_skills
        self.provider = OllamaProvider(
            base_url=settings.ollama_url,
            model=settings.default_model,
            timeout=float(settings.timeout),
        )

        # Use a fast model for routing if specified, otherwise use default
        self.routing_model = settings.default_model
        if settings.needle_model_path:
            self.routing_model = settings.needle_model_path

    async def close(self) -> None:
        """Clean up resources."""
        await self.provider.close()

    async def plan(self, user_request: str, context: Optional[str] = None) -> ExecutionPlan:
        """
        Generate an execution plan for the user request.

        Args:
            user_request: The user's task/request
            context: Optional project context

        Returns:
            ExecutionPlan with selected skills and tools
        """
        # Build the routing prompt
        prompt = self._build_routing_prompt(user_request, context)

        # Get routing decision from model
        response = await self.provider.chat(
            messages=[OllamaMessage(role="user", content=prompt)],
            system_prompt=self._get_system_prompt(),
            temperature=0.1,  # Low temperature for deterministic routing
            top_p=0.5,
        )

        # Parse the response into an ExecutionPlan
        plan = self._parse_response(response.message.content, user_request)

        return plan

    def _get_system_prompt(self) -> str:
        """Get the system prompt for Needle routing."""
        return """You are Needle, a precise tool routing engine for LocalCoder.

Your task is to analyze user requests and generate structured execution plans.

OUTPUT FORMAT:
You MUST output a valid JSON object with this exact structure:

{
    "intent": "brief_description_of_user_intent",
    "skills": [
        {"name": "skill_name", "confidence": 0.95, "reason": "why_this_skill"}
    ],
    "tools": [
        {"name": "tool_name", "arguments": {"arg1": "value1", "arg2": "value2"}}
    ],
    "requires_confirmation": false,
    "summary": "Brief summary of what will be done"
}

RULES:
1. ALWAYS output valid JSON - no markdown, no explanations outside JSON
2. If the task can be completed with tools, include them in the "tools" array
3. Set requires_confirmation=true for dangerous operations (delete, sudo, etc.)
4. Skills are optional - only include if relevant
5. Tools must match the available tool names exactly
6. Arguments must match the tool schemas

AVAILABLE TOOLS:
{tools}

AVAILABLE SKILLS:
{skills}

If NO tools are needed (pure Q&A), return an empty tools array.
If the request is unclear, ask for clarification in the summary field."""

    def _build_routing_prompt(
        self, user_request: str, context: Optional[str] = None
    ) -> str:
        """Build the complete routing prompt."""
        tools_json = json.dumps(self.available_tools, indent=2)
        skills_json = json.dumps(self.available_skills, indent=2)

        prompt = f"""User Request: {user_request}

AVAILABLE TOOLS:
{tools_json}

AVAILABLE SKILLS:
{skills_json}
"""

        if context:
            prompt += f"\nPROJECT CONTEXT:\n{context}\n"

        prompt += "\nGenerate the execution plan as JSON:"

        return prompt

    def _parse_response(self, response_content: str, user_request: str) -> ExecutionPlan:
        """Parse the model response into an ExecutionPlan."""
        # Extract JSON from response (handle markdown code blocks)
        json_str = self._extract_json(response_content)

        try:
            data = json.loads(json_str)
        except json.JSONDecodeError:
            # Fallback: create a minimal plan
            return ExecutionPlan(
                intent="unknown",
                summary=f"Could not parse routing response: {response_content[:200]}",
            )

        # Parse skills
        skills = []
        for skill_data in data.get("skills", []):
            skills.append(
                SkillSelection(
                    name=skill_data.get("name", ""),
                    confidence=skill_data.get("confidence", 0.5),
                    reason=skill_data.get("reason", ""),
                )
            )

        # Parse tools
        tools = []
        for tool_data in data.get("tools", []):
            tools.append(
                ToolCall(
                    name=tool_data.get("name", ""),
                    arguments=tool_data.get("arguments", {}),
                    description=tool_data.get("description", ""),
                )
            )

        return ExecutionPlan(
            intent=data.get("intent", "unknown"),
            skills=skills,
            tools=tools,
            requires_confirmation=data.get("requires_confirmation", False),
            summary=data.get("summary", ""),
        )

    def _extract_json(self, text: str) -> str:
        """Extract JSON string from text (handles markdown code blocks)."""
        # Try to find JSON between curly braces
        json_match = re.search(r"\{[\s\S]*\}", text)
        if json_match:
            return json_match.group(0)

        # Try to extract from markdown code block
        code_match = re.search(r"```(?:json)?\s*([\s\S]*?)\s*```", text)
        if code_match:
            return code_match.group(1)

        # Return as-is and let JSON parsing fail
        return text.strip()


class SkillRegistry:
    """Registry for managing available skills."""

    def __init__(self, skills_dir: Path):
        self.skills_dir = skills_dir
        self._skills: list[dict] = []
        self._load_skills()

    def _load_skills(self) -> None:
        """Load skills from the skills directory."""
        if not self.skills_dir.exists():
            return

        for skill_dir in self.skills_dir.iterdir():
            if not skill_dir.is_dir():
                continue

            skill_info = self._load_skill(skill_dir)
            if skill_info:
                self._skills.append(skill_info)

    def _load_skill(self, skill_dir: Path) -> Optional[dict]:
        """Load a single skill from its directory."""
        skill_md = skill_dir / "skill.md"
        if not skill_md.exists():
            return None

        # Read skill metadata
        content = skill_md.read_text(encoding="utf-8")

        # Parse simple YAML-like frontmatter
        name = skill_dir.name
        description = ""
        allowed_tools = []

        for line in content.split("\n"):
            if line.startswith("name:"):
                name = line.split(":", 1)[1].strip()
            elif line.startswith("description:"):
                description = line.split(":", 1)[1].strip()
            elif line.startswith("allowed_tools:"):
                tools_str = line.split(":", 1)[1].strip()
                allowed_tools = [t.strip() for t in tools_str.split(",")]

        # Load allowed tools from JSON if exists
        allowed_tools_file = skill_dir / "allowed_tools.json"
        if allowed_tools_file.exists():
            try:
                allowed_tools = json.loads(allowed_tools_file.read_text())
            except (json.JSONDecodeError, FileNotFoundError):
                pass

        return {
            "name": name,
            "description": description,
            "directory": str(skill_dir),
            "allowed_tools": allowed_tools,
        }

    def get_skills(self) -> list[dict]:
        """Get all available skills."""
        return self._skills.copy()

    def get_skill_by_name(self, name: str) -> Optional[dict]:
        """Get a specific skill by name."""
        for skill in self._skills:
            if skill["name"] == name:
                return skill
        return None
